networks:
  bot_network:
    driver: bridge

services:
  bot:
    build: .
    container_name: fileify-bot
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - bot_network

  redis:
    image: redis:7-alpine
    container_name: fileify-redis
    restart: unless-stopped
    networks:
      - bot_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:
